=== Dylan-Daza-Celis/venta-boletos/schema/database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="eventos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="conciertos">
          <xs:complexType><xs:sequence>
            <xs:element name="concierto" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType><xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="artista" type="xs:string"/>
                <xs:element name="lugar" type="xs:string"/>
                <xs:element name="fecha" type="xs:date"/>
                <xs:element name="hora" type="xs:time"/>
                <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
                <xs:element name="imagen" type="xs:anyURI" minOccurs="0"/>
                <xs:element name="boletos"><xs:complexType><xs:sequence>
                  <xs:element name="boleto" maxOccurs="unbounded"><xs:complexType><xs:sequence>
                    <xs:element name="tipo" type="xs:string"/>
                    <xs:element name="precio" type="xs:decimal"/>
                    <xs:element name="disponibles" type="xs:nonNegativeInteger"/>
                  </xs:sequence></xs:complexType></xs:element>
                </xs:sequence></xs:complexType></xs:element>
              </xs:sequence><xs:attribute name="id" type="xs:string" use="required"/></xs:complexType>
            </xs:element>
          </xs:sequence></xs:complexType>
        </xs:element>
        <xs:element name="compras"><xs:complexType><xs:sequence>
          <xs:element name="compra" minOccurs="0" maxOccurs="unbounded"><xs:complexType><xs:sequence>
            <xs:element name="conciertoId" type="xs:string"/>
            <xs:element name="tipoBoleto" type="xs:string"/>
            <xs:element name="cantidad" type="xs:positiveInteger"/>
            <xs:element name="fechaCompra" type="xs:dateTime"/>
            <xs:element name="usuarioId" type="xs:string"/>
          </xs:sequence><xs:attribute name="id" type="xs:string" use="required"/></xs:complexType></xs:element>
        </xs:sequence></xs:complexType></xs:element>
        <xs:element name="usuarios" minOccurs="0"><xs:complexType><xs:sequence>
          <xs:element name="usuario" minOccurs="0" maxOccurs="unbounded"><xs:complexType><xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
            <xs:element name="nombre" type="xs:string" minOccurs="0"/>
            <xs:element name="apellidoPaterno" type="xs:string" minOccurs="0"/>
            <xs:element name="apellidoMaterno" type="xs:string" minOccurs="0"/>
            <xs:element name="diaNacimiento" type="xs:positiveInteger" minOccurs="0"/>
            <xs:element name="mesNacimiento" type="xs:positiveInteger" minOccurs="0"/>
            <xs:element name="anioNacimiento" type="xs:positiveInteger" minOccurs="0"/>
            <xs:element name="genero" type="xs:string" minOccurs="0"/>
            <xs:element name="correo" type="xs:string" minOccurs="0"/>
            <xs:element name="telefono" type="xs:string" minOccurs="0"/>
            <xs:element name="rol" type="xs:string"/>
          </xs:sequence><xs:attribute name="id" type="xs:string" use="required"/></xs:complexType></xs:element>
        </xs:sequence></xs:complexType></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Dylan-Daza-Celis/venta-boletos/data/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/views/database.xsl"?>
<eventos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/database.xsd">
  <conciertos>
    <concierto id="878e6df8-b27b-4beb-8390-0bc056b32087">
      <nombre>YEM</nombre>
      <artista>morat</artista>
      <lugar>GNP</lugar>
      <fecha>2026-12-11</fecha>
      <hora>22:00:00</hora>
      <descripcion>UNA NOCHE DE BAILE Y RECUERDOS INOLVIDABLE</descripcion>
      <imagen>/images/morat.jpeg</imagen>
      <boletos>
        <boleto>
          <tipo>General</tipo>
          <precio>1000</precio>
          <disponibles>5</disponibles>
        </boleto>
        <boleto>
          <tipo>VIP</tipo>
          <precio>3000</precio>
          <disponibles>0</disponibles>
        </boleto>
      </boletos>
    </concierto>
    <concierto id="7e89e73e-e995-45be-be55-226001dd3288">
      <nombre>CAPUAVENTURES</nombre>
      <artista>Nieto de Capulina</artista>
      <lugar>CU</lugar>
      <fecha>2026-12-12</fecha>
      <hora>00:00:00</hora>
      <imagen>/images/capulina.jpg</imagen>
      <descripcion>Pasatela bien chicle bomba con el nietototote de capulinitititota</descripcion>
      <generalPrecio>6700</generalPrecio>
      <generalDisponibles>670</generalDisponibles>
      <vipPrecio>6700</vipPrecio>
      <vipDisponibles>67</vipDisponibles>
      <boletos>
        <boleto>
          <tipo>General</tipo>
          <precio>6700</precio>
          <disponibles>670</disponibles>
        </boleto>
        <boleto>
          <tipo>VIP</tipo>
          <precio>6700</precio>
          <disponibles>67</disponibles>
        </boleto>
      </boletos>
    </concierto>
    <concierto id="d937bc11-6db2-4377-8363-759eed44ded3">
      <nombre>Los Guapos</nombre>
      <artista>Mateo Yo Guapo</artista>
      <lugar>GNP</lugar>
      <fecha>2026-02-12</fecha>
      <hora>21:00:00</hora>
      <descripcion>Que me pota, Yo vapo</descripcion>
      <imagen>/images/mateo.jpg</imagen>
      <boletos>
        <boleto>
          <tipo>General</tipo>
          <precio>67</precio>
          <disponibles>67</disponibles>
        </boleto>
        <boleto>
          <tipo>VIP</tipo>
          <precio>67</precio>
          <disponibles>66</disponibles>
        </boleto>
      </boletos>
    </concierto>
  </conciertos>
  <compras>
    <compra id="c7012054-3d03-497e-9cdd-8c360e3a5c22">
      <conciertoId>878e6df8-b27b-4beb-8390-0bc056b32087</conciertoId>
      <tipoBoleto>VIP</tipoBoleto>
      <cantidad>3</cantidad>
      <fechaCompra>2026-10-20T21:49:08.403Z</fechaCompra>
      <usuarioId>768806c8-86ba-4a3f-ad11-5e18ba05cb13</usuarioId>
    </compra>
    <compra id="6fab209b-fa3f-4d24-a788-aa2490881f52">
      <conciertoId>d937bc11-6db2-4377-8363-759eed44ded3</conciertoId>
      <tipoBoleto>VIP</tipoBoleto>
      <cantidad>1</cantidad>
      <fechaCompra>2026-10-20T22:01:07.178Z</fechaCompra>
      <usuarioId>0cbdf491-8f2f-465b-ab33-f1cbe95659e6</usuarioId>
    </compra>
  </compras>
  <usuarios>
    <usuario id="cb057a4f-bba3-4fea-b69b-57677ab6a829">
      <username>admin</username>
      <password>5c1525569ffb8199a2386cfe8a59bdd9:eee00b442c50b74e0cab2fa56b3c3d7c72a4cd4753fcbcd9d00c91bc591caaacbc46b69a1f9864069b296a5c93b1c1d868fdd0b59975ee381f5f2e5d0dde6560</password>
      <rol>admin</rol>
    </usuario>
    <usuario id="fb013cae-de6a-400c-8fc4-d9744a0b3dea">
      <username>dylan</username>
      <password>a2afb8162d9d1c22b1b50a216d6e8c63:b48b57ed7803473d9e909c3193a52fe3c8dcf6bdd528827d06b4b42c6e989912616cd00053845367c73591d9dbbcb97b69686f82db3535d2af0293bbe5320612</password>
      <rol>usuario</rol>
    </usuario>
    <usuario id="768806c8-86ba-4a3f-ad11-5e18ba05cb13">
      <username>dylan_clss</username>
      <password>825c0cebea201985ff4f0c9e3195a875:c81f5da2ff2990f0b0b796b32673bc0c88624fe2872bb76a5bbedde8660d41039f394fc8cdc7951af3b087a708dc98adab8d93da4f52a12fbfbdacb19083cbcd</password>
      <nombre>Dylan</nombre>
      <apellidoPaterno>Daza</apellidoPaterno>
      <apellidoMaterno>Celis</apellidoMaterno>
      <diaNacimiento>17</diaNacimiento>
      <mesNacimiento>5</mesNacimiento>
      <anioNacimiento>2004</anioNacimiento>
      <genero>Hombre</genero>
      <correo>dylancelis6a@gmail.com</correo>
      <telefono>2214403318</telefono>
      <rol>usuario</rol>
    </usuario>
    <usuario id="0cbdf491-8f2f-465b-ab33-f1cbe95659e6">
      <username>diego</username>
      <password>4ab02f5edcba5ed681c281d2084bc05b:6c5528c00292908cf8e6fe54bf4d1d5ce20afdd12fbcc4edf2bf08348fa48441f01765cb83491202c2d5200ab03fd50d139689e0606bc6e2863fc6b6994318f6</password>
      <nombre>Diego</nombre>
      <apellidoPaterno>Gonzalz</apellidoPaterno>
      <apellidoMaterno>Camarillo</apellidoMaterno>
      <diaNacimiento>26</diaNacimiento>
      <mesNacimiento>2</mesNacimiento>
      <anioNacimiento>2004</anioNacimiento>
      <genero>Hombre</genero>
      <correo>diegogonzalezcamarillo@gmail.com</correo>
      <telefono>2202140823</telefono>
      <rol>usuario</rol>
    </usuario>
  </usuarios>
</eventos>
